<?php
$clasificados = array(
	array('id'=>'1','nombre'=>'Productos y Otros','clasificados_id'=>NULL),
	array('id'=>'1747','nombre'=>'Accesorios para Vehículos','clasificados_id'=>'1'),
	array('id'=>'26399','nombre'=>'Accesorios Náuticos','clasificados_id'=>'1747'),
	array('id'=>'5732','nombre'=>'Accesorios para Carros','clasificados_id'=>'1747'),
	array('id'=>'5727','nombre'=>'Accesorios para Motos','clasificados_id'=>'1747'),
	array('id'=>'17895','nombre'=>'Accesorios para Rústicos','clasificados_id'=>'1747'),
	array('id'=>'3381','nombre'=>'Audio para Carros','clasificados_id'=>'1747'),
	array('id'=>'8471','nombre'=>'Autoperiquitos','clasificados_id'=>'1747'),
	array('id'=>'8561','nombre'=>'Herramientas para Carros','clasificados_id'=>'1747'),
	array('id'=>'8531','nombre'=>'Navegadores GPS','clasificados_id'=>'1747'),
	array('id'=>'2232','nombre'=>'Otros','clasificados_id'=>'1747'),
	array('id'=>'1071','nombre'=>'Animales y Mascotas','clasificados_id'=>'1'),
	array('id'=>'8592','nombre'=>'Alimentación para Animales','clasificados_id'=>'1071'),
	array('id'=>'1081','nombre'=>'Gatos','clasificados_id'=>'1071'),
	array('id'=>'3615','nombre'=>'Libros de Animales','clasificados_id'=>'1071'),
	array('id'=>'1072','nombre'=>'Perros','clasificados_id'=>'1071'),
	array('id'=>'1126','nombre'=>'Otros Accesorios para Animales','clasificados_id'=>'1071'),
	array('id'=>'1384','nombre'=>'Bebés','clasificados_id'=>'1'),
	array('id'=>'5360','nombre'=>'Alimentación para Bebés','clasificados_id'=>'1384'),
	array('id'=>'74766','nombre'=>'Andaderas','clasificados_id'=>'1384'),
	array('id'=>'5373','nombre'=>'Artículos de Bebés para Baño','clasificados_id'=>'1384'),
	array('id'=>'40402','nombre'=>'Canguros y Porta Bebés','clasificados_id'=>'1384'),
	array('id'=>'1386','nombre'=>'Coches para Bebés','clasificados_id'=>'1384'),
	array('id'=>'1388','nombre'=>'Corrales, Cunas y Moisés','clasificados_id'=>'1384'),
	array('id'=>'1392','nombre'=>'Juguetes para Bebés','clasificados_id'=>'1384'),
	array('id'=>'8591','nombre'=>'Recuerdos y Cotillones de Bebé','clasificados_id'=>'1384'),
	array('id'=>'1396','nombre'=>'Ropa de Bebé','clasificados_id'=>'1384'),
	array('id'=>'1390','nombre'=>'Seguridad para Bebés','clasificados_id'=>'1384'),
	array('id'=>'1387','nombre'=>'Sillas de Bebés para Carros','clasificados_id'=>'1384'),
	array('id'=>'40428','nombre'=>'Sillas de Bebés para Comer','clasificados_id'=>'1384'),
	array('id'=>'1889','nombre'=>'Otros','clasificados_id'=>'1384'),
	array('id'=>'1051','nombre'=>'Celulares y Teléfonos','clasificados_id'=>'1'),
	array('id'=>'3813','nombre'=>'Accesorios para Celulares','clasificados_id'=>'1051'),
	array('id'=>'8359','nombre'=>'Adaptadores USB','clasificados_id'=>'3813'),
	array('id'=>'4922','nombre'=>'Cables de Datos','clasificados_id'=>'3813'),
	array('id'=>'72118','nombre'=>'BlackBerry','clasificados_id'=>'4922'),
	array('id'=>'117190','nombre'=>'iPhone','clasificados_id'=>'4922'),
	array('id'=>'5306','nombre'=>'Motorola','clasificados_id'=>'4922'),
	array('id'=>'5305','nombre'=>'Nokia','clasificados_id'=>'4922'),
	array('id'=>'6303','nombre'=>'Samsung','clasificados_id'=>'4922'),
	array('id'=>'6290','nombre'=>'Sony','clasificados_id'=>'4922'),
	array('id'=>'5304','nombre'=>'Otras Marcas','clasificados_id'=>'4922'),
	array('id'=>'2904','nombre'=>'Cargadores','clasificados_id'=>'3813'),
	array('id'=>'58322','nombre'=>'BlackBerry','clasificados_id'=>'2904'),
	array('id'=>'117195','nombre'=>'Genéricos','clasificados_id'=>'2904'),
	array('id'=>'72126','nombre'=>'HTC','clasificados_id'=>'2904'),
	array('id'=>'48017','nombre'=>'iPhone','clasificados_id'=>'2904'),
	array('id'=>'72130','nombre'=>'LG','clasificados_id'=>'2904'),
	array('id'=>'4163','nombre'=>'Motorola','clasificados_id'=>'2904'),
	array('id'=>'4164','nombre'=>'Nokia','clasificados_id'=>'2904'),
	array('id'=>'117194','nombre'=>'Power Bank','clasificados_id'=>'2904'),
	array('id'=>'4167','nombre'=>'Samsung','clasificados_id'=>'2904'),
	array('id'=>'4162','nombre'=>'Sony','clasificados_id'=>'2904'),
	array('id'=>'4165','nombre'=>'Otras Marcas','clasificados_id'=>'2904'),
	array('id'=>'11860','nombre'=>'Cornetas','clasificados_id'=>'3813'),
	array('id'=>'5213','nombre'=>'Estuches y Forros','clasificados_id'=>'3813'),
	array('id'=>'117252','nombre'=>'Láminas Protectoras','clasificados_id'=>'3813'),
	array('id'=>'39109','nombre'=>'Lápices','clasificados_id'=>'3813'),
	array('id'=>'5072','nombre'=>'Manos Libres','clasificados_id'=>'3813'),
	array('id'=>'117251','nombre'=>'Memorias MicroSD','clasificados_id'=>'3813'),
	array('id'=>'116924','nombre'=>'Smartwatch','clasificados_id'=>'3813'),
	array('id'=>'4160','nombre'=>'Tonos y Software','clasificados_id'=>'3813'),
	array('id'=>'4187','nombre'=>'Otros','clasificados_id'=>'3813'),
	array('id'=>'1055','nombre'=>'Celulares y Smartphones','clasificados_id'=>'1051'),
	array('id'=>'10616','nombre'=>'Centros de Comunicaciones','clasificados_id'=>'1051'),
	array('id'=>'1058','nombre'=>'Radios - WalkieTalkies','clasificados_id'=>'1051'),
	array('id'=>'117272','nombre'=>'Repuestos para Celulares','clasificados_id'=>'1051'),
	array('id'=>'1053','nombre'=>'Telefonía','clasificados_id'=>'1051'),
	array('id'=>'1915','nombre'=>'Otros','clasificados_id'=>'1051'),
	array('id'=>'1798','nombre'=>'Coleccionables y Hobbies','clasificados_id'=>'1	'),
	array('id'=>'16319','nombre'=>'Bolígrafos','clasificados_id'=>'1798'),
	array('id'=>'16320','nombre'=>'Calcomanías','clasificados_id'=>'1798'),
	array('id'=>'16308','nombre'=>'Chapas y Pines','clasificados_id'=>'1798'),
	array('id'=>'3435','nombre'=>'Comics','clasificados_id'=>'1798'),
	array('id'=>'3422','nombre'=>'Figuras y Muñecos','clasificados_id'=>'1798'),
	array('id'=>'1861','nombre'=>'Filatelia','clasificados_id'=>'1798'),
	array('id'=>'8366','nombre'=>'Fotografías','clasificados_id'=>'1798'),
	array('id'=>'2314','nombre'=>'Latas, Botellas y Afines','clasificados_id'=>'1798'),
	array('id'=>'1805','nombre'=>'Militaría y Afines','clasificados_id'=>'1798'),
	array('id'=>'3407','nombre'=>'Modelismo','clasificados_id'=>'1798'),
	array('id'=>'1806','nombre'=>'Monedas y Billetes Venezolanos','clasificados_id'=>'1798'),
	array('id'=>'1807','nombre'=>'Postales','clasificados_id'=>'1798'),
	array('id'=>'1830','nombre'=>'Tarjetas Telefónicas','clasificados_id'=>'1798'),
	array('id'=>'111067','nombre'=>'Vehículos en Miniatura','clasificados_id'=>'1798'),
	array('id'=>'1831','nombre'=>'Álbumes y Cromos','clasificados_id'=>'1798'),
	array('id'=>'2458','nombre'=>'Otros','clasificados_id'=>'1798'),
	array('id'=>'1648','nombre'=>'Computación','clasificados_id'=>'1'),
	array('id'=>'3377','nombre'=>'Accesorios para Laptops','clasificados_id'=>'1648'),
	array('id'=>'1870','nombre'=>'Apple','clasificados_id'=>'1648'),
	array('id'=>'2141','nombre'=>'Cartuchos, Tintas y Toner','clasificados_id'=>'1648'),
	array('id'=>'1691','nombre'=>'Componentes de PC','clasificados_id'=>'1648'),
	array('id'=>'1649','nombre'=>'Computadoras','clasificados_id'=>'1648'),
	array('id'=>'9533','nombre'=>'Discos Duros y Removibles','clasificados_id'=>'1648'),
	array('id'=>'1676','nombre'=>'Impresoras y Plotters','clasificados_id'=>'1648'),
	array('id'=>'1652','nombre'=>'Laptops','clasificados_id'=>'1648'),
	array('id'=>'1694','nombre'=>'Memorias RAM','clasificados_id'=>'1648'),
	array('id'=>'1656','nombre'=>'Monitores','clasificados_id'=>'1648'),
	array('id'=>'1714','nombre'=>'Mouses','clasificados_id'=>'1648'),
	array('id'=>'1651','nombre'=>'Palms y Pocket PC´s','clasificados_id'=>'1648'),
	array('id'=>'5027','nombre'=>'Pen Drives','clasificados_id'=>'1648'),
	array('id'=>'1712','nombre'=>'Periféricos y Accesorios de PC','clasificados_id'=>'1648'),
	array('id'=>'1693','nombre'=>'Procesadores','clasificados_id'=>'1648'),
	array('id'=>'1657','nombre'=>'Proyectores y Pantallas','clasificados_id'=>'1648'),
	array('id'=>'1670','nombre'=>'Quemadoras y Discos Vírgenes','clasificados_id'=>'1648'),
	array('id'=>'1709','nombre'=>'Redes Inalámbricas','clasificados_id'=>'1648'),
	array('id'=>'1700','nombre'=>'Redes No Inalámbricas','clasificados_id'=>'1648'),
	array('id'=>'8883','nombre'=>'Registradoras y Punto de Venta','clasificados_id'=>'1648'),
	array('id'=>'1723','nombre'=>'Software','clasificados_id'=>'1648'),
	array('id'=>'117283','nombre'=>'Tablets y Accesorios','clasificados_id'=>'1648'),
	array('id'=>'1658','nombre'=>'Tarjetas de Video y Captura','clasificados_id'=>'1648'),
	array('id'=>'1692','nombre'=>'Tarjetas Madre','clasificados_id'=>'1648'),
	array('id'=>'1912','nombre'=>'Otros','clasificados_id'=>'1648'),
	array('id'=>'1144','nombre'=>'Consolas y Videojuegos','clasificados_id'=>'1'),
	array('id'=>'3778','nombre'=>'GameBoy','clasificados_id'=>'1144'),
	array('id'=>'4394','nombre'=>'GameCube','clasificados_id'=>'1144'),
	array('id'=>'92662','nombre'=>'Nintendo 3DS','clasificados_id'=>'1144'),
	array('id'=>'4395','nombre'=>'Nintendo 64','clasificados_id'=>'1144'),
	array('id'=>'11050','nombre'=>'Nintendo DS','clasificados_id'=>'1144'),
	array('id'=>'11223','nombre'=>'Nintendo Wii','clasificados_id'=>'1144'),
	array('id'=>'116346','nombre'=>'Nintendo Wii U','clasificados_id'=>'1144'),
	array('id'=>'6004','nombre'=>'PlayStation 1','clasificados_id'=>'1144'),
	array('id'=>'5998','nombre'=>'PlayStation 2 - PS2','clasificados_id'=>'1144'),
	array('id'=>'11623','nombre'=>'PlayStation 3 - PS3','clasificados_id'=>'1144'),
	array('id'=>'116499','nombre'=>'PlayStation 4 - PS4','clasificados_id'=>'1144'),
	array('id'=>'8735','nombre'=>'PlayStation Portable - PSP','clasificados_id'=>'1144'),
	array('id'=>'106931','nombre'=>'PlayStation Vita - PS Vita','clasificados_id'=>'1144'),
	array('id'=>'9826','nombre'=>'Xbox','clasificados_id'=>'1144'),
	array('id'=>'9959','nombre'=>'Xbox 360','clasificados_id'=>'1144'),
	array('id'=>'116734','nombre'=>'Xbox One','clasificados_id'=>'1144'),
	array('id'=>'1152','nombre'=>'Otras Consolas','clasificados_id'=>'1144'),
	array('id'=>'1039','nombre'=>'Cámaras y Accesorios','clasificados_id'=>'1'),
	array('id'=>'1049','nombre'=>'Accesorios para Cámaras','clasificados_id'=>'1039'),
	array('id'=>'2889','nombre'=>'Cámaras Convencionales','clasificados_id'=>'1039'),
	array('id'=>'1042','nombre'=>'Cámaras Digitales','clasificados_id'=>'1039'),
	array('id'=>'5215','nombre'=>'Memorias Digitales','clasificados_id'=>'1039'),
	array('id'=>'4660','nombre'=>'Video Cámaras','clasificados_id'=>'1039'),
	array('id'=>'1914','nombre'=>'Otros','clasificados_id'=>'1039'),
	array('id'=>'1276','nombre'=>'Deportes y Fitness','clasificados_id'=>'1'),
	array('id'=>'1338','nombre'=>'Aerobics y Fitness','clasificados_id'=>'1276'),
	array('id'=>'2480','nombre'=>'Artes Marciales y Boxeo','clasificados_id'=>'1276'),
	array('id'=>'1328','nombre'=>'Beisbol','clasificados_id'=>'1276'),
	array('id'=>'1292','nombre'=>'Bicicletas y Ciclismo','clasificados_id'=>'1276'),
	array('id'=>'18109','nombre'=>'Bowling','clasificados_id'=>'1276'),
	array('id'=>'1362','nombre'=>'Camping','clasificados_id'=>'1276'),
	array('id'=>'1277','nombre'=>'Deportes Acuáticos','clasificados_id'=>'1276'),
	array('id'=>'3611','nombre'=>'Deportes Extremos','clasificados_id'=>'1276'),
	array('id'=>'1979','nombre'=>'Equipos para Pesca','clasificados_id'=>'1276'),
	array('id'=>'1285','nombre'=>'Fútbol','clasificados_id'=>'1276'),
	array('id'=>'18113','nombre'=>'Golf','clasificados_id'=>'1276'),
	array('id'=>'4697','nombre'=>'Juegos de Salón','clasificados_id'=>'1276'),
	array('id'=>'8776','nombre'=>'Lentes Deportivos y de Sol','clasificados_id'=>'1276'),
	array('id'=>'8843','nombre'=>'Morrales, Koalas y Maletines','clasificados_id'=>'1276'),
	array('id'=>'8635','nombre'=>'Máquinas de Gimnasio','clasificados_id'=>'1276'),
	array('id'=>'1293','nombre'=>'Patines','clasificados_id'=>'1276'),
	array('id'=>'79735','nombre'=>'Skate','clasificados_id'=>'1276	'),
	array('id'=>'6144','nombre'=>'Tenis y Squash','clasificados_id'=>'1276'),
	array('id'=>'5479','nombre'=>'Zapatos Deportivos','clasificados_id'=>'1276'),
	array('id'=>'1358','nombre'=>'Otros','clasificados_id'=>'1276'),
	array('id'=>'5726','nombre'=>'Electrodomésticos','clasificados_id'=>'1'),
	array('id'=>'112138','nombre'=>'Aires Acondicionados','clasificados_id'=>'5726'),
	array('id'=>'1578','nombre'=>'Artefactos para el Hogar','clasificados_id'=>'5726'),
	array('id'=>'8458','nombre'=>'Electrodomésticos de Cocina','clasificados_id'=>'5726'),
	array('id'=>'27576','nombre'=>'Lavadoras y Secadoras','clasificados_id'=>'5726'),
	array('id'=>'1576','nombre'=>'Neveras y Congeladores','clasificados_id'=>'5726'),
	array('id'=>'1645','nombre'=>'Ventiladores','clasificados_id'=>'5726'),
	array('id'=>'5977','nombre'=>'Otros','clasificados_id'=>'5726'),
	array('id'=>'1000','nombre'=>'Electrónica, Audio y Video','clasificados_id'=>'1'),
	array('id'=>'8886','nombre'=>'Accesorios para Audio y Video','clasificados_id'=>'1000'),
	array('id'=>'1023','nombre'=>'Audio para Carros','clasificados_id'=>'1000'),
	array('id'=>'3835','nombre'=>'Audio para el Hogar','clasificados_id'=>'1000'),
	array('id'=>'8626','nombre'=>'Audio Portátil y Radios','clasificados_id'=>'1000'),
	array('id'=>'3837','nombre'=>'Audio Profesional y DJs','clasificados_id'=>'1000'),
	array('id'=>'1060','nombre'=>'Calculadoras','clasificados_id'=>'1000'),
	array('id'=>'1001','nombre'=>'DVDs y Home Theaters','clasificados_id'=>'1000'),
	array('id'=>'1941','nombre'=>'Fotocopiadoras y Accesorios','clasificados_id'=>'1000'),
	array('id'=>'6473','nombre'=>'GPS y Accesorios','clasificados_id'=>'1000'),
	array('id'=>'8702','nombre'=>'iPod','clasificados_id'=>'1000'),
	array('id'=>'1012','nombre'=>'Reproductores MP3, MP4 y MP5','clasificados_id'=>'1000'),
	array('id'=>'2912','nombre'=>'Seguridad para el Hogar','clasificados_id'=>'1000'),
	array('id'=>'1002','nombre'=>'TV - Televisores','clasificados_id'=>'1000'),
	array('id'=>'1006','nombre'=>'Video Cámaras','clasificados_id'=>'1000'),
	array('id'=>'1070','nombre'=>'Otros','clasificados_id'=>'1000'),
	array('id'=>'1246','nombre'=>'Estética y Belleza','clasificados_id'=>'1'),
	array('id'=>'1253','nombre'=>'Cuidado de la Piel','clasificados_id'=>'1246'),
	array('id'=>'1263','nombre'=>'Cuidado del Cabello','clasificados_id'=>'1246'),
	array('id'=>'29762','nombre'=>'Cuidado para Uñas','clasificados_id'=>'1246'),
	array('id'=>'8631','nombre'=>'Cuidado Personal','clasificados_id'=>'1246'),
	array('id'=>'1248','nombre'=>'Maquillaje','clasificados_id'=>'1246'),
	array('id'=>'1271','nombre'=>'Perfumes y Fragancias','clasificados_id'=>'1246'),
	array('id'=>'1275','nombre'=>'Otros','clasificados_id'=>'1246'),
	array('id'=>'1574','nombre'=>'Hogar y Muebles','clasificados_id'=>'1'),
	array('id'=>'116335','nombre'=>'Artículos para Navidad','clasificados_id'=>'1574'),
	array('id'=>'1613','nombre'=>'Baño','clasificados_id'=>'1574'),
	array('id'=>'1618','nombre'=>'Cocina','clasificados_id'=>'1574'),
	array('id'=>'1631','nombre'=>'Decoración','clasificados_id'=>'1574'),
	array('id'=>'1608','nombre'=>'Dormitorio','clasificados_id'=>'1574'),
	array('id'=>'2525','nombre'=>'Herramientas para el Hogar','clasificados_id'=>'1574'),
	array('id'=>'1582','nombre'=>'Iluminación para el Hogar','clasificados_id'=>'1574'),
	array('id'=>'8406','nombre'=>'Jardín','clasificados_id'=>'1574'),
	array('id'=>'3236','nombre'=>'Sala y Comedor','clasificados_id'=>'1574'),
	array('id'=>'31399','nombre'=>'Otros','clasificados_id'=>'1574'),
	array('id'=>'1499','nombre'=>'Industrias','clasificados_id'=>'1'),
	array('id'=>'1500','nombre'=>'Construcción','clasificados_id'=>'1499'),
	array('id'=>'2467','nombre'=>'Energia Eléctrica','clasificados_id'=>'1499'),
	array('id'=>'5226','nombre'=>'Herramientas','clasificados_id'=>'1499'),
	array('id'=>'29758','nombre'=>'Industria Alimentaria','clasificados_id'=>'1499'),
	array('id'=>'29759','nombre'=>'Industria Textil','clasificados_id'=>'1499'),
	array('id'=>'8535','nombre'=>'Oficinas','clasificados_id'=>'1499'),
	array('id'=>'29757','nombre'=>'Publicidad y Mercadeo','clasificados_id'=>'1499'),
	array('id'=>'8515','nombre'=>'Seguridad para Industrias','clasificados_id'=>'1499'),
	array('id'=>'8530','nombre'=>'Testers y Multímetros','clasificados_id'=>'1499'),
	array('id'=>'1893','nombre'=>'Otros','clasificados_id'=>'1499'),
	array('id'=>'1182','nombre'=>'Instrumentos Musicales','clasificados_id'=>'1'),
	array('id'=>'8553','nombre'=>'Audio Profesional y DJs','clasificados_id'=>'8553'),
	array('id'=>'3018','nombre'=>'Bajos','clasificados_id'=>'8553'),
	array('id'=>'3004','nombre'=>'Baterías y Percusión','clasificados_id'=>'8553	'),
	array('id'=>'3012','nombre'=>'Efectos de Sonido','clasificados_id'=>'8553'),
	array('id'=>'2987','nombre'=>'Guitarras','clasificados_id'=>'8553'),
	array('id'=>'3005','nombre'=>'Instrumentos de Viento','clasificados_id'=>'8553'),
	array('id'=>'2997','nombre'=>'Teclados y Pianos','clasificados_id'=>'8553'),
	array('id'=>'3023','nombre'=>'Violines','clasificados_id'=>'8553'),
	array('id'=>'7805','nombre'=>'Órganos','clasificados_id'=>'8553'),
	array('id'=>'3014','nombre'=>'Otros','clasificados_id'=>'8553	'),
	array('id'=>'1132','nombre'=>'Juegos y Juguetes','clasificados_id'=>'1'),
	array('id'=>'2978','nombre'=>'Figuras y Muñecos','clasificados_id'=>'1132'),
	array('id'=>'2960','nombre'=>'Juegos','clasificados_id'=>'1132'),
	array('id'=>'10813','nombre'=>'Juegos al Aire Libre y Agua','clasificados_id'=>'1132'),
	array('id'=>'2533','nombre'=>'Juguetes','clasificados_id'=>'1132'),
	array('id'=>'8370','nombre'=>'Juguetes para Bebés','clasificados_id'=>'1132'),
	array('id'=>'1841','nombre'=>'Modelismo','clasificados_id'=>'1132'),
	array('id'=>'2968','nombre'=>'Muñecas y Accesorios','clasificados_id'=>'1132'),
	array('id'=>'111073','nombre'=>'Vehículos en Miniatura','clasificados_id'=>'1132'),
	array('id'=>'10811','nombre'=>'Vehículos para Niños','clasificados_id'=>'1132'),
	array('id'=>'1910','nombre'=>'Otros','clasificados_id'=>'1132'),
	array('id'=>'3025','nombre'=>'Libros, Música y Películas','clasificados_id'=>'1'),
	array('id'=>'80266','nombre'=>'Afiches de Películas y Libros','clasificados_id'=>'3025'),
	array('id'=>'3043','nombre'=>'Comics','clasificados_id'=>'3025'),
	array('id'=>'7529','nombre'=>'E-books','clasificados_id'=>'3025'),
	array('id'=>'1196','nombre'=>'Libros','clasificados_id'=>'3025'),
	array('id'=>'1176','nombre'=>'Música y Videos','clasificados_id'=>'3025'),
	array('id'=>'1169','nombre'=>'Películas','clasificados_id'=>'3025'),
	array('id'=>'1955','nombre'=>'Revistas','clasificados_id'=>'3025'),
	array('id'=>'6217','nombre'=>'Series de TV y Telenovelas','clasificados_id'=>'3025'),
	array('id'=>'1228','nombre'=>'Otros','clasificados_id'=>'3025'),
	array('id'=>'3937','nombre'=>'Relojes, Joyas y Bisutería','clasificados_id'=>'1'),
	array('id'=>'1431','nombre'=>'Joyería y Bisutería','clasificados_id'=>'3937'),
	array('id'=>'7715','nombre'=>'Materiales para Joyería','clasificados_id'=>'3937'),
	array('id'=>'1442','nombre'=>'Relojes','clasificados_id'=>'3937'),
	array('id'=>'3938','nombre'=>'Otros','clasificados_id'=>'3937'),
	array('id'=>'1430','nombre'=>'Ropa, Zapatos y Accesorios','clasificados_id'=>'1'),
	array('id'=>'8820','nombre'=>'Accesorios de Moda','clasificados_id'=>'1430'),
	array('id'=>'116898','nombre'=>'Blusas','clasificados_id'=>'1430'),
	array('id'=>'116867','nombre'=>'Camisas','clasificados_id'=>'1430'),
	array('id'=>'26400','nombre'=>'Carteras, Morrales y Billetera','clasificados_id'=>'1430'),
	array('id'=>'116909','nombre'=>'Chaquetas','clasificados_id'=>'1430'),
	array('id'=>'116859','nombre'=>'Chemises','clasificados_id'=>'1430'),
	array('id'=>'3123','nombre'=>'Conjuntos para Niños','clasificados_id'=>'1430'),
	array('id'=>'24787','nombre'=>'Disfraces para Niños','clasificados_id'=>'1430'),
	array('id'=>'116862','nombre'=>'Faldas','clasificados_id'=>'1430'),
	array('id'=>'116883','nombre'=>'Franelas','clasificados_id'=>'1430'),
	array('id'=>'116845','nombre'=>'Jeans','clasificados_id'=>'1430'),
	array('id'=>'116856','nombre'=>'Pantalones','clasificados_id'=>'1430'),
	array('id'=>'116849','nombre'=>'Pijamas y Ropa de Dormir','clasificados_id'=>'1430'),
	array('id'=>'116864','nombre'=>'Ropa Interior','clasificados_id'=>'1430'),
	array('id'=>'24621','nombre'=>'Ropa para Bebés','clasificados_id'=>'1430'),
	array('id'=>'116824','nombre'=>'Shorts y Bermudas','clasificados_id'=>'1430'),
	array('id'=>'116853','nombre'=>'Sweaters','clasificados_id'=>'1430'),
	array('id'=>'116841','nombre'=>'Trajes de Baño','clasificados_id'=>'1430'),
	array('id'=>'116827','nombre'=>'Vestidos','clasificados_id'=>'1430'),
	array('id'=>'5299','nombre'=>'Vestidos de Novia','clasificados_id'=>'1430'),
	array('id'=>'5208','nombre'=>'Zapatos','clasificados_id'=>'1430'),
	array('id'=>'9865','nombre'=>'Zapatos Deportivos','clasificados_id'=>'1430'),
	array('id'=>'1911','nombre'=>'Otros','clasificados_id'=>'1430'),
	array('id'=>'1953','nombre'=>'Otras Categorías','clasificados_id'=>'1'),
	array('id'=>'2818','nombre'=>'Adultos','clasificados_id'=>'1953'),
	array('id'=>'1367','nombre'=>'Arte y Antigüedades','clasificados_id'=>'1953'),
	array('id'=>'1403','nombre'=>'Bebidas y Alimentos','clasificados_id'=>'1953'),
	array('id'=>'1740','nombre'=>'Esoterismo','clasificados_id'=>'1953'),
	array('id'=>'40433','nombre'=>'Eventos y Conciertos','clasificados_id'=>'1953'),
	array('id'=>'44011','nombre'=>'Recuerdos y Cotillones','clasificados_id'=>'1953'),
	array('id'=>'3530','nombre'=>'Otros','clasificados_id'=>'1953'),
	array('id'=>'2','nombre'=>'Servicios','clasificados_id'=>NULL),
	array('id'=>'3','nombre'=>'Inmuebles','clasificados_id'=>NULL),
	array('id'=>'4','nombre'=>'Vehículos','clasificados_id'=>NULL)		
);

$naturales = array(
	array("nombre"=>"Romel","apellido"=>"Flores","email"=>"romelfloresl@gmail.com","direccion"=>"P.O. Box 280, 468 Et Ave","telefono"=>"0338-006-2728","descripcion"=>"nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla","tipo"=>"V","identificacion"=>19865260),
	array("nombre"=>"Jean","apellido"=>"Alviarez","email"=>"jeanalviarez@gmail.com","direccion"=>"P.O. Box 650, 6231 Enim, Av.","telefono"=>"0147-490-2399","descripcion"=>"consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem","tipo"=>"V","identificacion"=>19236990),
	array("nombre"=>"Quinn","apellido"=>"Bishop","email"=>"velit.Quisque.varius@necligulaconsectetuer.ca","direccion"=>"P.O. Box 876, 1340 Sit Road","telefono"=>"0595-165-4663","descripcion"=>"tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat","tipo"=>"V","identificacion"=>25201240),
	array("nombre"=>"Sage","apellido"=>"Glover","email"=>"egestas@laoreetliberoet.org","direccion"=>"P.O. Box 174, 8616 Lobortis Rd.","telefono"=>"0388-428-1131","descripcion"=>"ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi","tipo"=>"V","identificacion"=>75010207),
	array("nombre"=>"Ursula","apellido"=>"Huff","email"=>"elit@augueSed.org","direccion"=>"536-9964 Vestibulum Av.","telefono"=>"0904-099-5892","descripcion"=>"massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor","tipo"=>"V","identificacion"=>19328578),
	array("nombre"=>"Venus","apellido"=>"Norman","email"=>"metus@utsemNulla.co.uk","direccion"=>"464-7156 Montes, St.","telefono"=>"0209-150-0486","descripcion"=>"fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit","tipo"=>"V","identificacion"=>43786360),
	array("nombre"=>"Malik","apellido"=>"Mcclain","email"=>"non.justo.Proin@nasceturridiculusmus.edu","direccion"=>"6187 Lobortis. Ave","telefono"=>"0129-182-8842","descripcion"=>"ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas","tipo"=>"V","identificacion"=>30773052),
	array("nombre"=>"Christian","apellido"=>"Obrien","email"=>"sollicitudin@nec.co.uk","direccion"=>"P.O. Box 979, 4925 Nibh Road","telefono"=>"0563-740-7221","descripcion"=>"Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis.","tipo"=>"V","identificacion"=>98088717),
	array("nombre"=>"Jade","apellido"=>"Obrien","email"=>"justo@inaliquet.org","direccion"=>"Ap #520-9395 Maecenas St.","telefono"=>"0988-809-0785","descripcion"=>"massa. Suspendisse eleifend. Cras sed","tipo"=>"V","identificacion"=>26448389),
	array("nombre"=>"Whoopi","apellido"=>"Emerson","email"=>"lectus.justo.eu@aliquetPhasellus.com","direccion"=>"Ap #849-3451 Urna. Street","telefono"=>"0620-426-4545","descripcion"=>"a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate","tipo"=>"V","identificacion"=>90722739),
	array("nombre"=>"Candice","apellido"=>"Spencer","email"=>"Nunc@nonjusto.net","direccion"=>"P.O. Box 991, 296 Sodales Avenue","telefono"=>"0036-668-2426","descripcion"=>"mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada.","tipo"=>"E","identificacion"=>29648186),
	array("nombre"=>"Ray","apellido"=>"Mccarty","email"=>"Vivamus.molestie.dapibus@felisegetvarius.co.uk","direccion"=>"P.O. Box 939, 2916 Cras Ave","telefono"=>"0081-407-6562","descripcion"=>"enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor","tipo"=>"E","identificacion"=>26370973),
	array("nombre"=>"Blythe","apellido"=>"Swanson","email"=>"turpis.vitae@dictumcursus.com","direccion"=>"799-7466 Adipiscing Road","telefono"=>"0233-678-3125","descripcion"=>"libero.","tipo"=>"E","identificacion"=>73068876),
	array("nombre"=>"Chase","apellido"=>"Vargas","email"=>"egestas.urna.justo@sitametrisus.org","direccion"=>"P.O. Box 871, 5331 Et Ave","telefono"=>"0380-485-4277","descripcion"=>"orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis","tipo"=>"E","identificacion"=>50885369),
	array("nombre"=>"Desirae","apellido"=>"Mann","email"=>"fames.ac@mauris.co.uk","direccion"=>"3477 Tellus Ave","telefono"=>"0212-362-7096","descripcion"=>"In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non","tipo"=>"E","identificacion"=>59889572),
	array("nombre"=>"Garrison","apellido"=>"Spencer","email"=>"volutpat.Nulla@Phaselluslibero.ca","direccion"=>"Ap #252-135 Cubilia Road","telefono"=>"0118-285-8412","descripcion"=>"lorem vitae","tipo"=>"E","identificacion"=>37638484),
	array("nombre"=>"Ferris","apellido"=>"Wise","email"=>"eget.venenatis.a@quismassaMauris.edu","direccion"=>"896-723 Facilisis Street","telefono"=>"0710-267-8618","descripcion"=>"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","tipo"=>"E","identificacion"=>52221752),
	array("nombre"=>"Eleanor","apellido"=>"Valenzuela","email"=>"iaculis.aliquet@Sednulla.co.uk","direccion"=>"P.O. Box 418, 9046 Tincidunt, Ave","telefono"=>"0083-774-4951","descripcion"=>"tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est","tipo"=>"E","identificacion"=>49706821),
	array("nombre"=>"Bo","apellido"=>"Moon","email"=>"erat.eget@nuncsed.net","direccion"=>"Ap #430-9780 Ante. St.","telefono"=>"0631-667-9659","descripcion"=>"cursus. Nunc mauris elit,","tipo"=>"E","identificacion"=>21052845),
	array("nombre"=>"Oleg","apellido"=>"Woods","email"=>"in.magna@actellus.com","direccion"=>"260-3440 Aliquet St.","telefono"=>"0043-718-6484","descripcion"=>"blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum","tipo"=>"E","identificacion"=>60005019),
	array("nombre"=>"Derek","apellido"=>"Taylor","email"=>"magna.sed@ullamcorpervelitin.edu","direccion"=>"844-4649 Elit, Street","telefono"=>"0103-247-3219","descripcion"=>"et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent","tipo"=>"P","identificacion"=>49392837),
	array("nombre"=>"Linus","apellido"=>"Norris","email"=>"ut.quam.vel@elitEtiamlaoreet.edu","direccion"=>"Ap #184-6008 Vel, Road","telefono"=>"0135-910-4124","descripcion"=>"nibh","tipo"=>"P","identificacion"=>73319616),
	array("nombre"=>"Omar","apellido"=>"Horton","email"=>"ligula@rutrumurna.net","direccion"=>"6319 Aliquam Av.","telefono"=>"0278-871-3184","descripcion"=>"justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum.","tipo"=>"P","identificacion"=>27352405),
	array("nombre"=>"Jade","apellido"=>"Mullins","email"=>"sociis.natoque@Cras.org","direccion"=>"P.O. Box 604, 7265 Rutrum Road","telefono"=>"0935-589-1665","descripcion"=>"Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis,","tipo"=>"P","identificacion"=>53371857),
	array("nombre"=>"Jonah","apellido"=>"Roy","email"=>"erat.nonummy@sodalesnisimagna.edu","direccion"=>"Ap #614-669 At Av.","telefono"=>"0617-137-8092","descripcion"=>"nec tempus mauris erat eget ipsum.","tipo"=>"P","identificacion"=>17195493),
	array("nombre"=>"Kato","apellido"=>"Berry","email"=>"semper.auctor.Mauris@augueid.edu","direccion"=>"397-1373 Proin Rd.","telefono"=>"0103-031-4630","descripcion"=>"commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede.","tipo"=>"P","identificacion"=>53460148),
	array("nombre"=>"Cherokee","apellido"=>"Johnston","email"=>"nisi.magna.sed@Donecluctusaliquet.net","direccion"=>"392-7345 Nunc Road","telefono"=>"0194-124-3776","descripcion"=>"orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus","tipo"=>"P","identificacion"=>88694720),
	array("nombre"=>"Karen","apellido"=>"Morton","email"=>"vitae.semper.egestas@ataugueid.com","direccion"=>"1249 At Road","telefono"=>"0342-023-6918","descripcion"=>"vel, mauris. Integer","tipo"=>"P","identificacion"=>28983433),
	array("nombre"=>"Jesse","apellido"=>"Maddox","email"=>"arcu.Sed.eu@risus.co.uk","direccion"=>"248-2960 Ornare, Street","telefono"=>"0257-705-5155","descripcion"=>"eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient","tipo"=>"P","identificacion"=>86359239),
	array("nombre"=>"Frances","apellido"=>"Holman","email"=>"amet@Cras.co.uk","direccion"=>"138-6426 Pharetra Ave","telefono"=>"0150-539-8472","descripcion"=>"sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque","tipo"=>"P","identificacion"=>66160703),
	array("nombre"=>"Ulric","apellido"=>"Robbins","email"=>"Vestibulum.ante@lectusquis.co.uk","direccion"=>"P.O. Box 918, 711 Nunc Avenue","telefono"=>"0586-249-3143","descripcion"=>"sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi.","tipo"=>"V","identificacion"=>61221977),
	array("nombre"=>"Cyrus","apellido"=>"Garrison","email"=>"Fusce.aliquet@gravidaPraesent.com","direccion"=>"P.O. Box 291, 760 At Street","telefono"=>"0992-828-6983","descripcion"=>"diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis","tipo"=>"V","identificacion"=>44630036),
	array("nombre"=>"Burke","apellido"=>"Solis","email"=>"feugiat@in.edu","direccion"=>"683-2389 Elementum, Avenue","telefono"=>"0930-762-6868","descripcion"=>"semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec","tipo"=>"V","identificacion"=>59953076),
	array("nombre"=>"Arsenio","apellido"=>"Orr","email"=>"Phasellus.dapibus.quam@musProin.edu","direccion"=>"P.O. Box 795, 7062 Ultrices St.","telefono"=>"0345-567-9101","descripcion"=>"Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas.","tipo"=>"V","identificacion"=>94759833),
	array("nombre"=>"Chase","apellido"=>"Goodman","email"=>"nunc.sed@Nullamvitaediam.org","direccion"=>"Ap #940-1898 Mauris. Rd.","telefono"=>"0211-121-3510","descripcion"=>"vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum","tipo"=>"V","identificacion"=>11124012),
	array("nombre"=>"Jarrod","apellido"=>"Brewer","email"=>"consectetuer.adipiscing.elit@et.edu","direccion"=>"P.O. Box 803, 4442 Ipsum Av.","telefono"=>"0059-107-9292","descripcion"=>"varius. Nam porttitor","tipo"=>"V","identificacion"=>49090972),
	array("nombre"=>"Cassandra","apellido"=>"Palmer","email"=>"ante.Nunc.mauris@facilisis.com","direccion"=>"P.O. Box 738, 3543 Magna Rd.","telefono"=>"0221-249-9203","descripcion"=>"quam. Curabitur vel lectus. Cum sociis","tipo"=>"V","identificacion"=>58213799),
	array("nombre"=>"Harrison","apellido"=>"Pittman","email"=>"Vivamus@ornare.edu","direccion"=>"Ap #673-5251 Sit Avenue","telefono"=>"0555-085-7607","descripcion"=>"Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim.","tipo"=>"V","identificacion"=>35431983),
	array("nombre"=>"Kasper","apellido"=>"Noble","email"=>"convallis.est@fringillaDonecfeugiat.org","direccion"=>"4798 Lorem Av.","telefono"=>"0587-613-8008","descripcion"=>"nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere","tipo"=>"V","identificacion"=>21759196),
	array("nombre"=>"Ross","apellido"=>"Moss","email"=>"Sed.nec@Phasellus.net","direccion"=>"P.O. Box 479, 6735 Dignissim. Rd.","telefono"=>"0209-021-5028","descripcion"=>"sed","tipo"=>"V","identificacion"=>63279743),
	array("nombre"=>"Anastasia","apellido"=>"Barrera","email"=>"nonummy.ut@eu.co.uk","direccion"=>"547-2331 Natoque St.","telefono"=>"0582-272-7931","descripcion"=>"eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent","tipo"=>"E","identificacion"=>56850335),
	array("nombre"=>"Garrett","apellido"=>"Stephenson","email"=>"cursus@nuncinterdum.edu","direccion"=>"P.O. Box 717, 9900 Proin Avenue","telefono"=>"0853-623-4648","descripcion"=>"et pede. Nunc sed orci lobortis augue scelerisque mollis.","tipo"=>"E","identificacion"=>48811813),
	array("nombre"=>"Donovan","apellido"=>"Leblanc","email"=>"est.mollis@egestasSedpharetra.org","direccion"=>"897-7340 Urna St.","telefono"=>"0182-148-0027","descripcion"=>"feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim","tipo"=>"E","identificacion"=>34579251),
	array("nombre"=>"Valentine","apellido"=>"Wyatt","email"=>"pede.malesuada.vel@ultricesposuerecubilia.co.uk","direccion"=>"Ap #756-480 Luctus Rd.","telefono"=>"0049-792-2688","descripcion"=>"id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus","tipo"=>"E","identificacion"=>84572376),
	array("nombre"=>"Kiona","apellido"=>"Christensen","email"=>"aliquet@euismod.org","direccion"=>"279-5592 Amet Road","telefono"=>"0655-989-9290","descripcion"=>"eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam","tipo"=>"E","identificacion"=>58118222),
	array("nombre"=>"Adrienne","apellido"=>"Trevino","email"=>"odio@tincidunt.com","direccion"=>"P.O. Box 536, 2890 Cum Rd.","telefono"=>"0912-924-8325","descripcion"=>"nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum","tipo"=>"E","identificacion"=>90371916),
	array("nombre"=>"Cedric","apellido"=>"Montgomery","email"=>"dignissim.magna@Fuscealiquet.com","direccion"=>"P.O. Box 485, 9446 Eu Rd.","telefono"=>"0437-016-9891","descripcion"=>"justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna","tipo"=>"E","identificacion"=>76906670),
	array("nombre"=>"Hermione","apellido"=>"Knowles","email"=>"nec.mollis@nuncid.ca","direccion"=>"7579 Libero Street","telefono"=>"0261-081-1880","descripcion"=>"luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis","tipo"=>"E","identificacion"=>17746244),
	array("nombre"=>"Timon","apellido"=>"Lynn","email"=>"dictum@anteNunc.ca","direccion"=>"5412 Pede. Road","telefono"=>"0899-983-7691","descripcion"=>"lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor,","tipo"=>"E","identificacion"=>18998255),
	array("nombre"=>"Francesca","apellido"=>"Booth","email"=>"Donec.non@nuncrisus.edu","direccion"=>"Ap #299-4657 Nulla Rd.","telefono"=>"0635-440-3828","descripcion"=>"arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non,","tipo"=>"E","identificacion"=>86626621),
	array("nombre"=>"Fay","apellido"=>"Stevens","email"=>"gravida@felispurus.edu","direccion"=>"951-5834 Ut Ave","telefono"=>"0729-942-2688","descripcion"=>"Morbi non sapien molestie orci tincidunt","tipo"=>"P","identificacion"=>73831652),
	array("nombre"=>"Brynne","apellido"=>"Whitley","email"=>"gravida.Aliquam@placerat.ca","direccion"=>"860 Hendrerit Street","telefono"=>"0048-834-1364","descripcion"=>"neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc","tipo"=>"P","identificacion"=>48828559),
	array("nombre"=>"Hayley","apellido"=>"Curry","email"=>"vel.convallis@volutpatNullafacilisis.ca","direccion"=>"P.O. Box 358, 7519 Duis Av.","telefono"=>"0446-966-4935","descripcion"=>"magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer","tipo"=>"P","identificacion"=>13420406),
	array("nombre"=>"Kasper","apellido"=>"Tyson","email"=>"ac.mattis.ornare@bibendumsedest.com","direccion"=>"Ap #991-4437 Congue. Street","telefono"=>"0116-412-8079","descripcion"=>"Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue","tipo"=>"P","identificacion"=>98555225),
	array("nombre"=>"Colleen","apellido"=>"Anderson","email"=>"non.enim@maurisblanditmattis.edu","direccion"=>"239-9327 Aliquam Rd.","telefono"=>"0205-584-9836","descripcion"=>"sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque","tipo"=>"P","identificacion"=>85343486),
	array("nombre"=>"Violet","apellido"=>"Townsend","email"=>"porta@ornarefacilisiseget.net","direccion"=>"P.O. Box 268, 7178 Libero. Av.","telefono"=>"0430-681-4593","descripcion"=>"sed turpis nec","tipo"=>"P","identificacion"=>25807539),
	array("nombre"=>"Reuben","apellido"=>"Lester","email"=>"nunc.id.enim@euenim.edu","direccion"=>"9536 Turpis. Av.","telefono"=>"0876-462-6498","descripcion"=>"a felis ullamcorper viverra. Maecenas iaculis aliquet diam.","tipo"=>"P","identificacion"=>46189849),
	array("nombre"=>"Maris","apellido"=>"Bonner","email"=>"fringilla@sociisnatoquepenatibus.com","direccion"=>"9109 A, Rd.","telefono"=>"0705-268-9972","descripcion"=>"Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque.","tipo"=>"P","identificacion"=>29946574),
	array("nombre"=>"Ali","apellido"=>"Pratt","email"=>"adipiscing@lacus.edu","direccion"=>"729-1049 Eu Road","telefono"=>"0354-026-4465","descripcion"=>"ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem","tipo"=>"P","identificacion"=>13502921),
	array("nombre"=>"Rafael","apellido"=>"Oneil","email"=>"urna.nec@maurissagittis.edu","direccion"=>"116-8382 Risus St.","telefono"=>"0032-653-6898","descripcion"=>"non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit,","tipo"=>"P","identificacion"=>55988899),
	array("nombre"=>"Fallon","apellido"=>"Guzman","email"=>"et.magnis.dis@nislQuisque.edu","direccion"=>"1792 Quam Rd.","telefono"=>"0355-117-8580","descripcion"=>"urna. Vivamus","tipo"=>"V","identificacion"=>64579786),
	array("nombre"=>"Daniel","apellido"=>"Ramirez","email"=>"metus.Aenean.sed@lectus.com","direccion"=>"1158 Augue Rd.","telefono"=>"0886-589-4250","descripcion"=>"semper et, lacinia vitae, sodales at, velit. Pellentesque","tipo"=>"V","identificacion"=>19680617),
	array("nombre"=>"Daria","apellido"=>"Terrell","email"=>"a@acfermentumvel.edu","direccion"=>"6932 Sed Avenue","telefono"=>"0073-797-0641","descripcion"=>"Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed","tipo"=>"V","identificacion"=>15968563),
	array("nombre"=>"Abra","apellido"=>"Britt","email"=>"ante.dictum@Proinvelarcu.co.uk","direccion"=>"Ap #815-4028 Et Ave","telefono"=>"0178-055-2615","descripcion"=>"facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend,","tipo"=>"V","identificacion"=>26351881),
	array("nombre"=>"Stuart","apellido"=>"Mathis","email"=>"erat@justonecante.com","direccion"=>"Ap #170-1870 Cum Road","telefono"=>"0165-474-9351","descripcion"=>"per","tipo"=>"V","identificacion"=>68991885),
	array("nombre"=>"Reece","apellido"=>"Flowers","email"=>"faucibus.orci@Sedneque.ca","direccion"=>"P.O. Box 278, 738 Augue Road","telefono"=>"0521-561-9272","descripcion"=>"tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus.","tipo"=>"V","identificacion"=>35744889),
	array("nombre"=>"Walker","apellido"=>"Carter","email"=>"dolor@semperpretiumneque.co.uk","direccion"=>"Ap #512-4368 Rhoncus. Street","telefono"=>"0238-484-3842","descripcion"=>"Proin non massa non ante bibendum","tipo"=>"V","identificacion"=>45644709),
	array("nombre"=>"Lucian","apellido"=>"Mclean","email"=>"vel.venenatis@loremipsumsodales.org","direccion"=>"P.O. Box 809, 9841 Dui Rd.","telefono"=>"0665-253-8099","descripcion"=>"imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor","tipo"=>"V","identificacion"=>77938262),
	array("nombre"=>"Ryder","apellido"=>"Page","email"=>"neque@molestieorcitincidunt.edu","direccion"=>"452-1970 Mus. Av.","telefono"=>"0441-862-3719","descripcion"=>"felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue,","tipo"=>"V","identificacion"=>97111635),
	array("nombre"=>"Ariel","apellido"=>"Chen","email"=>"magna.et@Crasdolordolor.edu","direccion"=>"Ap #207-3199 Cum Ave","telefono"=>"0797-492-6912","descripcion"=>"et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque","tipo"=>"V","identificacion"=>23983141),
	array("nombre"=>"Kim","apellido"=>"Fisher","email"=>"dolor.Quisque@egestasnuncsed.org","direccion"=>"P.O. Box 906, 9919 Nam Av.","telefono"=>"0979-053-4834","descripcion"=>"pellentesque a, facilisis non,","tipo"=>"E","identificacion"=>65817707),
	array("nombre"=>"Jasmine","apellido"=>"Hoover","email"=>"eleifend@nuncsed.net","direccion"=>"P.O. Box 875, 1122 Augue Avenue","telefono"=>"0720-018-4253","descripcion"=>"aliquet vel, vulputate eu, odio. Phasellus at augue id","tipo"=>"E","identificacion"=>28275735),
	array("nombre"=>"Kelsey","apellido"=>"Lopez","email"=>"ipsum.dolor.sit@MaurismagnaDuis.com","direccion"=>"4465 Morbi Road","telefono"=>"0807-658-8445","descripcion"=>"Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc","tipo"=>"E","identificacion"=>28603016),
	array("nombre"=>"Rafael","apellido"=>"Alford","email"=>"aliquam.eu@aultriciesadipiscing.com","direccion"=>"Ap #202-1423 Pede. Street","telefono"=>"0076-043-6659","descripcion"=>"eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel","tipo"=>"E","identificacion"=>99561427),
	array("nombre"=>"Kasper","apellido"=>"Giles","email"=>"ornare@nonenimcommodo.co.uk","direccion"=>"P.O. Box 981, 3964 In Avenue","telefono"=>"0815-818-6628","descripcion"=>"eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem.","tipo"=>"E","identificacion"=>97547443),
	array("nombre"=>"Drake","apellido"=>"Rosario","email"=>"neque.Sed.eget@Sedeu.co.uk","direccion"=>"Ap #327-1866 Egestas. Rd.","telefono"=>"0326-464-4664","descripcion"=>"sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris","tipo"=>"E","identificacion"=>40733267),
	array("nombre"=>"Laurel","apellido"=>"Noble","email"=>"eget@nec.org","direccion"=>"Ap #986-4639 Donec Rd.","telefono"=>"0394-728-9943","descripcion"=>"egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus","tipo"=>"E","identificacion"=>57530003),
	array("nombre"=>"Sonya","apellido"=>"Randall","email"=>"lorem.vehicula.et@conguea.com","direccion"=>"Ap #790-4281 Semper Rd.","telefono"=>"0058-778-0341","descripcion"=>"quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet","tipo"=>"E","identificacion"=>54525704),
	array("nombre"=>"Dorian","apellido"=>"Cash","email"=>"vestibulum.neque.sed@nuncac.org","direccion"=>"833-6619 Proin Avenue","telefono"=>"0944-138-4173","descripcion"=>"id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus","tipo"=>"E","identificacion"=>90612733),
	array("nombre"=>"Clio","apellido"=>"Wilkerson","email"=>"lorem@sit.net","direccion"=>"131-1896 Vivamus Avenue","telefono"=>"0396-541-3791","descripcion"=>"aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor,","tipo"=>"E","identificacion"=>94661222),
	array("nombre"=>"Shaine","apellido"=>"Collins","email"=>"consectetuer@auctor.co.uk","direccion"=>"Ap #690-7947 Molestie St.","telefono"=>"0375-168-1267","descripcion"=>"orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames","tipo"=>"P","identificacion"=>56178259),
	array("nombre"=>"Zahir","apellido"=>"Shaw","email"=>"auctor.nunc@Sednullaante.net","direccion"=>"P.O. Box 842, 7776 Arcu. Road","telefono"=>"0070-278-2703","descripcion"=>"Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at","tipo"=>"P","identificacion"=>77814928),
	array("nombre"=>"Adria","apellido"=>"Valentine","email"=>"tincidunt@nequevitae.edu","direccion"=>"9105 Tellus. Avenue","telefono"=>"0270-537-0105","descripcion"=>"sit amet orci. Ut sagittis lobortis mauris.","tipo"=>"P","identificacion"=>57775074),
	array("nombre"=>"Charles","apellido"=>"Snow","email"=>"tincidunt.dui@ultricesaauctor.org","direccion"=>"5580 Sem St.","telefono"=>"0108-838-1765","descripcion"=>"sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere,","tipo"=>"P","identificacion"=>67843290),
	array("nombre"=>"Kaseem","apellido"=>"Cash","email"=>"Cras.vulputate.velit@egetmetus.net","direccion"=>"165-323 Dignissim Street","telefono"=>"0461-912-9573","descripcion"=>"id sapien. Cras dolor dolor, tempus non, lacinia at,","tipo"=>"P","identificacion"=>12210205),
	array("nombre"=>"Avye","apellido"=>"Mcknight","email"=>"pede@Suspendisse.net","direccion"=>"394-970 Sagittis Rd.","telefono"=>"0186-377-2445","descripcion"=>"Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes,","tipo"=>"P","identificacion"=>72476395),
	array("nombre"=>"Carlos","apellido"=>"Ryan","email"=>"egestas.Sed@turpis.co.uk","direccion"=>"900-9931 Donec Rd.","telefono"=>"0923-525-8029","descripcion"=>"mauris ipsum porta elit, a feugiat","tipo"=>"P","identificacion"=>75143342),
	array("nombre"=>"Georgia","apellido"=>"Marks","email"=>"posuere.cubilia@rutrumFusce.net","direccion"=>"9396 Tempor Rd.","telefono"=>"0031-913-5362","descripcion"=>"Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit.","tipo"=>"P","identificacion"=>46872617),
	array("nombre"=>"Bruno","apellido"=>"Snow","email"=>"luctus.et@a.com","direccion"=>"P.O. Box 469, 7734 Quis St.","telefono"=>"0550-310-9789","descripcion"=>"sollicitudin a, malesuada id, erat. Etiam vestibulum","tipo"=>"P","identificacion"=>26257702),
	array("nombre"=>"Kylan","apellido"=>"Summers","email"=>"elit@maurisutmi.ca","direccion"=>"P.O. Box 996, 9753 Proin Rd.","telefono"=>"0724-584-4962","descripcion"=>"mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor","tipo"=>"P","identificacion"=>13303119),
	array("nombre"=>"Christian","apellido"=>"Aguirre","email"=>"imperdiet.erat.nonummy@id.net","direccion"=>"129-296 Turpis. Avenue","telefono"=>"0060-644-9616","descripcion"=>"tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia","tipo"=>"V","identificacion"=>37368662),
	array("nombre"=>"Sopoline","apellido"=>"Bass","email"=>"non.dapibus@orcilobortis.edu","direccion"=>"Ap #437-8139 Pellentesque. Ave","telefono"=>"0248-880-2509","descripcion"=>"eget tincidunt dui augue","tipo"=>"V","identificacion"=>96873442),
	array("nombre"=>"Warren","apellido"=>"Christensen","email"=>"faucibus.lectus.a@acfacilisisfacilisis.ca","direccion"=>"Ap #828-4008 Phasellus Rd.","telefono"=>"0809-838-8601","descripcion"=>"sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut","tipo"=>"V","identificacion"=>75848696),
	array("nombre"=>"Gisela","apellido"=>"Hensley","email"=>"pretium.aliquet.metus@convallisligulaDonec.ca","direccion"=>"P.O. Box 155, 8645 Mauris Ave","telefono"=>"0227-026-1882","descripcion"=>"egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper","tipo"=>"V","identificacion"=>86734080),
	array("nombre"=>"Plato","apellido"=>"Myers","email"=>"Fusce.diam@sodaleseliterat.ca","direccion"=>"625-1514 Tellus. St.","telefono"=>"0377-116-4997","descripcion"=>"sem elit, pharetra ut, pharetra sed, hendrerit a, arcu.","tipo"=>"V","identificacion"=>35611398),
	array("nombre"=>"Noble","apellido"=>"Berry","email"=>"tellus.id.nunc@Donecfringilla.org","direccion"=>"2500 Id Ave","telefono"=>"0192-462-7955","descripcion"=>"eu, euismod ac, fermentum","tipo"=>"V","identificacion"=>67303662),
	array("nombre"=>"Patricia","apellido"=>"Gaines","email"=>"at.augue@scelerisquescelerisquedui.com","direccion"=>"547-1943 Hymenaeos. Road","telefono"=>"0239-182-5834","descripcion"=>"Nullam vitae diam. Proin dolor. Nulla semper","tipo"=>"V","identificacion"=>43964879),
	array("nombre"=>"Hillary","apellido"=>"Hammond","email"=>"elementum.dui@semsemper.com","direccion"=>"921-2363 Dis St.","telefono"=>"0333-532-8647","descripcion"=>"Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus","tipo"=>"V","identificacion"=>26952314),
	array("nombre"=>"Renee","apellido"=>"Walter","email"=>"aliquam.eu@aaliquetvel.co.uk","direccion"=>"Ap #790-6977 Aliquam Av.","telefono"=>"0186-399-7963","descripcion"=>"pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet","tipo"=>"V","identificacion"=>11553280),
	array("nombre"=>"Jenna","apellido"=>"Roy","email"=>"vel.quam@sapien.org","direccion"=>"1255 In Avenue","telefono"=>"0709-569-0098","descripcion"=>"sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem,","tipo"=>"V","identificacion"=>46003657)
);


$juridicos  = array(
	array("razon_social"=>"Silicon Valley C.A.","email"=>"siliconvalley@gmail.com","direccion"=>"5080 Facilisis Road","telefono"=>"0904-373-2405","descripcion"=>"Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique","tipo"=>"J","rif"=>123456789),
	array("razon_social"=>"Fringilla Ornare Placerat Inc.","email"=>"quis@sollicitudinadipiscing.co.uk","direccion"=>"P.O. Box 191, 2012 Class Road","telefono"=>"0581-431-4717","descripcion"=>"ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu.","tipo"=>"J","rif"=>207082044),
	array("razon_social"=>"Feugiat Metus Sit Limited","email"=>"Nunc.mauris.sapien@euismod.ca","direccion"=>"P.O. Box 176, 729 Eu, Ave","telefono"=>"0371-562-7825","descripcion"=>"ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer","tipo"=>"J","rif"=>284299576),
	array("razon_social"=>"Lorem Vitae LLP","email"=>"morbi.tristique@Nullaaliquet.co.uk","direccion"=>"P.O. Box 933, 8053 A Av.","telefono"=>"0965-113-2478","descripcion"=>"erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis","tipo"=>"V","rif"=>250587933),
	array("razon_social"=>"Orci Tincidunt Adipiscing Consulting","email"=>"Nullam.ut@ipsumPhasellusvitae.com","direccion"=>"1077 At, Av.","telefono"=>"0624-446-3334","descripcion"=>"a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean","tipo"=>"V","rif"=>185482600),
	array("razon_social"=>"Maecenas Ornare Limited","email"=>"Cras.interdum.Nunc@ligulaNullamenim.edu","direccion"=>"789-7219 Porttitor Avenue","telefono"=>"0106-933-8826","descripcion"=>"vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc","tipo"=>"V","rif"=>232100999),
	array("razon_social"=>"Eget Dictum Placerat Institute","email"=>"ac.mattis.velit@auctornonfeugiat.co.uk","direccion"=>"144-4569 Magna. Avenue","telefono"=>"0408-422-7139","descripcion"=>"Quisque ac libero nec ligula consectetuer rhoncus. Nullam","tipo"=>"G","rif"=>127127712),
	array("razon_social"=>"Dapibus Id Incorporated","email"=>"odio.auctor@quamCurabiturvel.edu","direccion"=>"Ap #560-7908 Tortor Rd.","telefono"=>"0878-505-2824","descripcion"=>"justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit,","tipo"=>"G","rif"=>769278282),
	array("razon_social"=>"Fusce Mi Lorem Limited","email"=>"eget.tincidunt@Praesenteu.com","direccion"=>"P.O. Box 291, 1012 Tempus, Ave","telefono"=>"0715-975-6801","descripcion"=>"hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt","tipo"=>"G","rif"=>146832840),
	array("razon_social"=>"Eget Varius Ultrices Corporation","email"=>"Sed.nunc@malesuada.org","direccion"=>"560 Viverra. St.","telefono"=>"0192-352-2119","descripcion"=>"libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non,","tipo"=>"J","rif"=>687667770),
	array("razon_social"=>"Nulla Interdum LLP","email"=>"ultrices@nisl.net","direccion"=>"P.O. Box 432, 4425 Iaculis Road","telefono"=>"0032-082-0928","descripcion"=>"diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet","tipo"=>"J","rif"=>243571708),
	array("razon_social"=>"Erat Limited","email"=>"libero.Integer.in@placerat.org","direccion"=>"3056 Ligula St.","telefono"=>"0590-784-7933","descripcion"=>"dolor","tipo"=>"J","rif"=>977557909),
	array("razon_social"=>"Magna Duis Dignissim PC","email"=>"lobortis.tellus@malesuadavelconvallis.ca","direccion"=>"5918 Pretium Ave","telefono"=>"0553-481-0052","descripcion"=>"Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu,","tipo"=>"V","rif"=>426047604),
	array("razon_social"=>"Blandit Viverra Donec Associates","email"=>"metus.sit.amet@velitjustonec.net","direccion"=>"P.O. Box 741, 7979 Ante Rd.","telefono"=>"0904-415-5694","descripcion"=>"erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem,","tipo"=>"V","rif"=>277655577),
	array("razon_social"=>"Ad Litora LLC","email"=>"eget@orciquislectus.com","direccion"=>"Ap #593-5152 Donec St.","telefono"=>"0858-546-6748","descripcion"=>"senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque.","tipo"=>"V","rif"=>428502668),
	array("razon_social"=>"Blandit Mattis Cras Ltd","email"=>"nunc.In@nonquam.ca","direccion"=>"1364 Eget St.","telefono"=>"0999-562-3192","descripcion"=>"Pellentesque ut ipsum ac","tipo"=>"G","rif"=>305364266),
	array("razon_social"=>"Dui Corp.","email"=>"parturient.montes.nascetur@odioauctor.ca","direccion"=>"480-2747 Semper. Street","telefono"=>"0975-983-6165","descripcion"=>"primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse","tipo"=>"G","rif"=>496942621),
	array("razon_social"=>"Nibh Company","email"=>"Suspendisse@ultriciesadipiscingenim.net","direccion"=>"P.O. Box 118, 3598 At St.","telefono"=>"0134-921-3856","descripcion"=>"elementum, lorem ut aliquam iaculis,","tipo"=>"G","rif"=>976955191),
	array("razon_social"=>"Adipiscing Elit Aliquam Foundation","email"=>"justo.faucibus.lectus@ultricesposuere.com","direccion"=>"P.O. Box 904, 6385 Non St.","telefono"=>"0277-242-3965","descripcion"=>"molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id","tipo"=>"J","rif"=>198858927),
	array("razon_social"=>"Ac Feugiat Incorporated","email"=>"mollis@diamSeddiam.org","direccion"=>"Ap #189-8101 Sit Rd.","telefono"=>"0093-302-6705","descripcion"=>"eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu","tipo"=>"J","rif"=>153125888),
	array("razon_social"=>"Rutrum Corp.","email"=>"adipiscing.Mauris.molestie@nullavulputate.edu","direccion"=>"879-8062 Amet Ave","telefono"=>"0321-425-1631","descripcion"=>"urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis.","tipo"=>"J","rif"=>550321804),
	array("razon_social"=>"Orci Quis Corporation","email"=>"adipiscing.fringilla.porttitor@Etiamligula.org","direccion"=>"P.O. Box 660, 3531 Velit Street","telefono"=>"0497-555-0993","descripcion"=>"metus. Aenean sed pede","tipo"=>"V","rif"=>771307779),
	array("razon_social"=>"Turpis Nulla Aliquet LLP","email"=>"erat.vitae@egestas.org","direccion"=>"P.O. Box 506, 3778 Nam Avenue","telefono"=>"0652-065-2130","descripcion"=>"egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa.","tipo"=>"V","rif"=>166167091),
	array("razon_social"=>"Magna Incorporated","email"=>"posuere@viverraDonec.org","direccion"=>"P.O. Box 477, 8878 Tristique Rd.","telefono"=>"0301-446-2360","descripcion"=>"ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies","tipo"=>"V","rif"=>406985155),
	array("razon_social"=>"Pede Suspendisse Consulting","email"=>"Integer@dictumcursusNunc.org","direccion"=>"6564 Urna St.","telefono"=>"0093-551-4693","descripcion"=>"at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede,","tipo"=>"G","rif"=>153327043),
	array("razon_social"=>"Eleifend Vitae Erat PC","email"=>"dictum.cursus.Nunc@mauris.co.uk","direccion"=>"3635 Ligula Rd.","telefono"=>"0128-574-2839","descripcion"=>"ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec","tipo"=>"G","rif"=>878468275),
	array("razon_social"=>"Vitae Erat PC","email"=>"aliquam@metus.com","direccion"=>"Ap #846-2988 Sed Road","telefono"=>"0238-179-3629","descripcion"=>"Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer","tipo"=>"G","rif"=>928609440),
	array("razon_social"=>"Rutrum Eu Corporation","email"=>"Aenean@euismod.net","direccion"=>"Ap #355-8293 Nec Rd.","telefono"=>"0207-479-9368","descripcion"=>"aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet,","tipo"=>"J","rif"=>175726082),
	array("razon_social"=>"Parturient Montes Nascetur Corporation","email"=>"ut@est.ca","direccion"=>"4063 Donec Rd.","telefono"=>"0838-709-5574","descripcion"=>"vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet","tipo"=>"J","rif"=>556251142),
	array("razon_social"=>"Curae; Phasellus Ornare LLP","email"=>"vulputate@blandit.co.uk","direccion"=>"P.O. Box 653, 5828 Nisl Ave","telefono"=>"0819-788-3386","descripcion"=>"placerat, augue. Sed molestie. Sed id","tipo"=>"J","rif"=>457495931),
	array("razon_social"=>"Nunc Laoreet Lectus Incorporated","email"=>"pede@Maurisvestibulumneque.ca","direccion"=>"P.O. Box 788, 928 Non Rd.","telefono"=>"0083-122-5640","descripcion"=>"habitant morbi tristique senectus et netus et malesuada fames ac","tipo"=>"V","rif"=>395207621),
	array("razon_social"=>"Nibh Industries","email"=>"Donec.tincidunt.Donec@fringillaest.net","direccion"=>"Ap #651-4591 Elit, Rd.","telefono"=>"0150-698-6112","descripcion"=>"cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam","tipo"=>"V","rif"=>842051895),
	array("razon_social"=>"Cum Sociis Inc.","email"=>"Suspendisse.aliquet.sem@arcuimperdiet.com","direccion"=>"854-780 Vivamus St.","telefono"=>"0461-190-6780","descripcion"=>"mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus","tipo"=>"V","rif"=>178820315),
	array("razon_social"=>"Fringilla Cursus Industries","email"=>"scelerisque.lorem@non.net","direccion"=>"Ap #610-6397 Eu Street","telefono"=>"0540-650-7106","descripcion"=>"lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus","tipo"=>"G","rif"=>341211404),
	array("razon_social"=>"Vitae Sodales PC","email"=>"fringilla.ornare@quisarcuvel.com","direccion"=>"Ap #477-5153 Arcu. Rd.","telefono"=>"0272-078-2844","descripcion"=>"laoreet lectus quis massa.","tipo"=>"G","rif"=>213205889),
	array("razon_social"=>"Ornare Tortor At Incorporated","email"=>"cubilia@ullamcorper.ca","direccion"=>"291-4500 Fusce Street","telefono"=>"0399-352-2418","descripcion"=>"auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi","tipo"=>"G","rif"=>376202670),
	array("razon_social"=>"Non Hendrerit Id Institute","email"=>"dignissim.tempor.arcu@metuseuerat.com","direccion"=>"P.O. Box 170, 6970 Dolor, Street","telefono"=>"0453-541-0677","descripcion"=>"Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede","tipo"=>"J","rif"=>845729736),
	array("razon_social"=>"Pellentesque Habitant Morbi Inc.","email"=>"aliquet@sedhendrerita.org","direccion"=>"808-3081 Tristique St.","telefono"=>"0513-482-2900","descripcion"=>"arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere","tipo"=>"J","rif"=>323450799),
	array("razon_social"=>"Parturient Montes Inc.","email"=>"urna@primis.ca","direccion"=>"P.O. Box 405, 8877 Sed Ave","telefono"=>"0273-079-8278","descripcion"=>"egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.","tipo"=>"J","rif"=>914282152),
	array("razon_social"=>"Est Ac LLP","email"=>"varius.ultrices.mauris@metussitamet.ca","direccion"=>"P.O. Box 928, 5493 Vitae, Rd.","telefono"=>"0536-605-0444","descripcion"=>"lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu,","tipo"=>"V","rif"=>395164987),
	array("razon_social"=>"Arcu Ac LLC","email"=>"eu@dapibus.org","direccion"=>"394-5147 Dolor Av.","telefono"=>"0939-117-9353","descripcion"=>"lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo","tipo"=>"V","rif"=>740889438),
	array("razon_social"=>"Interdum Curabitur Dictum LLP","email"=>"Etiam@eratEtiam.org","direccion"=>"Ap #934-6990 Magna Ave","telefono"=>"0343-798-7050","descripcion"=>"ornare lectus justo eu","tipo"=>"V","rif"=>203299520),
	array("razon_social"=>"Parturient Inc.","email"=>"est.Mauris.eu@velitPellentesqueultricies.net","direccion"=>"1282 Congue. St.","telefono"=>"0095-634-3044","descripcion"=>"molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor,","tipo"=>"G","rif"=>581568252),
	array("razon_social"=>"Vulputate Foundation","email"=>"eleifend.nec@Morbi.net","direccion"=>"6993 Feugiat St.","telefono"=>"0880-629-9230","descripcion"=>"Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum.","tipo"=>"G","rif"=>142622564),
	array("razon_social"=>"Nam Consequat LLC","email"=>"vitae@Donecfelisorci.org","direccion"=>"P.O. Box 207, 1296 Erat, Ave","telefono"=>"0808-794-3961","descripcion"=>"convallis erat,","tipo"=>"G","rif"=>908002446),
	array("razon_social"=>"Nisi Cum Sociis LLC","email"=>"egestas@a.co.uk","direccion"=>"221-7670 Sagittis Rd.","telefono"=>"0804-833-7684","descripcion"=>"enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in","tipo"=>"J","rif"=>392868611),
	array("razon_social"=>"Eget Venenatis A Corp.","email"=>"ut.dolor.dapibus@urna.ca","direccion"=>"904-5002 Massa. Ave","telefono"=>"0702-096-1594","descripcion"=>"mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit","tipo"=>"J","rif"=>783859010),
	array("razon_social"=>"In Magna PC","email"=>"non.cursus@risus.com","direccion"=>"P.O. Box 227, 3390 Tellus Street","telefono"=>"0733-810-5227","descripcion"=>"et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus","tipo"=>"J","rif"=>985739301),
	array("razon_social"=>"Dictum Eu Eleifend LLP","email"=>"luctus.ut.pellentesque@liberoestcongue.co.uk","direccion"=>"3385 Vestibulum St.","telefono"=>"0798-918-7111","descripcion"=>"quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed","tipo"=>"V","rif"=>974438351),
	array("razon_social"=>"Pharetra LLP","email"=>"nulla.Integer.urna@porta.edu","direccion"=>"P.O. Box 288, 743 Id, Street","telefono"=>"0377-362-8937","descripcion"=>"erat","tipo"=>"V","rif"=>675756961),
	array("razon_social"=>"Duis Consulting","email"=>"scelerisque.dui.Suspendisse@ascelerisquesed.ca","direccion"=>"870-8634 Est, Road","telefono"=>"0390-856-1685","descripcion"=>"cursus luctus, ipsum leo elementum","tipo"=>"V","rif"=>115451831),
	array("razon_social"=>"Luctus Ipsum Associates","email"=>"tellus.eu.augue@turpisAliquamadipiscing.net","direccion"=>"370-8691 Mauris Av.","telefono"=>"0399-692-2632","descripcion"=>"Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus","tipo"=>"G","rif"=>828329593),
	array("razon_social"=>"Nulla PC","email"=>"eu.augue.porttitor@sodalesnisimagna.net","direccion"=>"Ap #507-9300 Sem Avenue","telefono"=>"0226-862-3672","descripcion"=>"mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam","tipo"=>"G","rif"=>382023562),
	array("razon_social"=>"Semper Cursus Integer Limited","email"=>"placerat.velit.Quisque@laciniavitaesodales.com","direccion"=>"Ap #856-923 Mi Rd.","telefono"=>"0212-750-6631","descripcion"=>"dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus.","tipo"=>"G","rif"=>461335692),
	array("razon_social"=>"Malesuada Fames Corporation","email"=>"dolor.quam.elementum@dictum.co.uk","direccion"=>"7615 Nulla Rd.","telefono"=>"0654-199-3280","descripcion"=>"ipsum leo elementum sem,","tipo"=>"J","rif"=>608701619),
	array("razon_social"=>"Dictum Placerat Augue LLC","email"=>"montes.nascetur.ridiculus@infelisNulla.org","direccion"=>"P.O. Box 358, 6329 Posuere Street","telefono"=>"0982-105-7825","descripcion"=>"et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio","tipo"=>"J","rif"=>916312282),
	array("razon_social"=>"Sed Malesuada Augue Consulting","email"=>"sit.amet@tinciduntpede.co.uk","direccion"=>"145-5081 Augue Avenue","telefono"=>"0831-244-5417","descripcion"=>"adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam","tipo"=>"J","rif"=>260746724),
	array("razon_social"=>"Volutpat Nunc Associates","email"=>"scelerisque.neque.sed@Aliquam.ca","direccion"=>"339-8279 Quisque Rd.","telefono"=>"0565-217-5157","descripcion"=>"id, blandit at, nisi. Cum sociis natoque","tipo"=>"V","rif"=>896220978),
	array("razon_social"=>"Sagittis Institute","email"=>"ante@aliquam.com","direccion"=>"Ap #428-7702 Pede Road","telefono"=>"0065-989-1715","descripcion"=>"fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl","tipo"=>"V","rif"=>118472194),
	array("razon_social"=>"A Tortor Corporation","email"=>"primis@nonummyipsumnon.ca","direccion"=>"P.O. Box 509, 6496 Dictum Ave","telefono"=>"0720-015-8594","descripcion"=>"erat semper rutrum.","tipo"=>"V","rif"=>206847222),
	array("razon_social"=>"At Velit Institute","email"=>"nec.eleifend@mi.co.uk","direccion"=>"Ap #864-3604 Felis, St.","telefono"=>"0077-464-3641","descripcion"=>"ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi","tipo"=>"G","rif"=>851003425),
	array("razon_social"=>"Vel Quam LLP","email"=>"cursus.in@Praesent.org","direccion"=>"Ap #203-7355 Mauris Avenue","telefono"=>"0934-684-9342","descripcion"=>"volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat","tipo"=>"G","rif"=>491976028),
	array("razon_social"=>"Nunc Mauris Inc.","email"=>"non.vestibulum@aceleifendvitae.ca","direccion"=>"Ap #309-3883 Erat St.","telefono"=>"0668-989-8726","descripcion"=>"eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis","tipo"=>"G","rif"=>208591218),
	array("razon_social"=>"Libero Donec Consectetuer Institute","email"=>"accumsan.neque.et@ornareegestasligula.ca","direccion"=>"102-2693 Mattis Ave","telefono"=>"0693-643-9286","descripcion"=>"interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui.","tipo"=>"J","rif"=>738103394),
	array("razon_social"=>"In PC","email"=>"eu@atpede.edu","direccion"=>"P.O. Box 387, 7338 Eu Av.","telefono"=>"0764-494-8507","descripcion"=>"magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt","tipo"=>"J","rif"=>461727472),
	array("razon_social"=>"Eget Foundation","email"=>"Maecenas@nonummyipsum.org","direccion"=>"P.O. Box 291, 1032 Feugiat Avenue","telefono"=>"0148-892-7877","descripcion"=>"luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut","tipo"=>"J","rif"=>540840210),
	array("razon_social"=>"Tempor Augue Ac LLC","email"=>"ut.dolor.dapibus@scelerisquenequesed.co.uk","direccion"=>"P.O. Box 800, 7236 Fusce St.","telefono"=>"0503-907-6141","descripcion"=>"varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus","tipo"=>"V","rif"=>994872844),
	array("razon_social"=>"Lobortis Quis Pede Ltd","email"=>"turpis@utlacusNulla.net","direccion"=>"4687 Mauris St.","telefono"=>"0402-719-5500","descripcion"=>"Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer","tipo"=>"V","rif"=>755253148),
	array("razon_social"=>"Mus Proin Vel LLP","email"=>"ipsum.primis@imperdiet.org","direccion"=>"P.O. Box 574, 1377 Vestibulum Street","telefono"=>"0859-322-9336","descripcion"=>"at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam","tipo"=>"V","rif"=>884295278),
	array("razon_social"=>"Metus Aliquam Associates","email"=>"felis@turpisvitae.co.uk","direccion"=>"478-2454 Enim, Av.","telefono"=>"0089-845-6792","descripcion"=>"ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in","tipo"=>"G","rif"=>305450284),
	array("razon_social"=>"Faucibus Morbi Limited","email"=>"mi@sedpede.net","direccion"=>"P.O. Box 475, 6786 Nulla Rd.","telefono"=>"0979-312-7049","descripcion"=>"tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus,","tipo"=>"G","rif"=>501476091),
	array("razon_social"=>"Velit Egestas Associates","email"=>"Maecenas@purussapien.ca","direccion"=>"145-5029 In Rd.","telefono"=>"0481-273-8926","descripcion"=>"imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci","tipo"=>"G","rif"=>415294875),
	array("razon_social"=>"Ligula Consectetuer Consulting","email"=>"eros@Namtempor.com","direccion"=>"609-3818 Lacus Avenue","telefono"=>"0615-185-8795","descripcion"=>"risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare,","tipo"=>"J","rif"=>892426206),
	array("razon_social"=>"Justo Sit Institute","email"=>"Sed@semsempererat.ca","direccion"=>"P.O. Box 956, 9115 Sed Ave","telefono"=>"0538-987-6360","descripcion"=>"fames ac","tipo"=>"J","rif"=>635843068),
	array("razon_social"=>"Risus Donec PC","email"=>"Pellentesque.ultricies@rhoncusDonecest.edu","direccion"=>"P.O. Box 264, 7043 Tristique Av.","telefono"=>"0108-649-9355","descripcion"=>"consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at","tipo"=>"J","rif"=>937657466),
	array("razon_social"=>"Morbi Tristique Senectus Industries","email"=>"pede.et@penatibuset.edu","direccion"=>"P.O. Box 205, 7564 Non, Ave","telefono"=>"0195-725-8244","descripcion"=>"lectus quis massa.","tipo"=>"V","rif"=>410928172),
	array("razon_social"=>"Nulla LLC","email"=>"nisl.Nulla@tempor.co.uk","direccion"=>"P.O. Box 222, 7348 At, Rd.","telefono"=>"0471-843-0530","descripcion"=>"purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean","tipo"=>"V","rif"=>977168912),
	array("razon_social"=>"Facilisis Associates","email"=>"iaculis.lacus.pede@dolor.ca","direccion"=>"P.O. Box 755, 6530 Sed Road","telefono"=>"0154-481-7709","descripcion"=>"Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit","tipo"=>"V","rif"=>415147348),
	array("razon_social"=>"Consequat Nec Mollis Company","email"=>"sit.amet@nisidictum.co.uk","direccion"=>"P.O. Box 847, 2053 Ligula Street","telefono"=>"0778-368-9152","descripcion"=>"ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula","tipo"=>"G","rif"=>645694551),
	array("razon_social"=>"Luctus Lobortis Class Foundation","email"=>"Suspendisse@neceuismod.net","direccion"=>"243-7467 Sem Avenue","telefono"=>"0993-276-6144","descripcion"=>"ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant","tipo"=>"G","rif"=>757773844),
	array("razon_social"=>"Consectetuer Cursus LLP","email"=>"lobortis.risus@augueeu.ca","direccion"=>"P.O. Box 613, 8302 Integer St.","telefono"=>"0246-563-2838","descripcion"=>"sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","tipo"=>"G","rif"=>926608003),
	array("razon_social"=>"Malesuada Consulting","email"=>"cursus.in.hendrerit@sit.ca","direccion"=>"764-6583 Ante. Av.","telefono"=>"0172-806-2488","descripcion"=>"Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id,","tipo"=>"J","rif"=>786549731),
	array("razon_social"=>"Lacus Pede Sagittis Limited","email"=>"Etiam.vestibulum@idlibero.co.uk","direccion"=>"585-7720 In, Rd.","telefono"=>"0880-294-6856","descripcion"=>"Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora","tipo"=>"J","rif"=>433164360),
	array("razon_social"=>"Urna Foundation","email"=>"vehicula@eu.ca","direccion"=>"P.O. Box 894, 9621 Donec Rd.","telefono"=>"0950-004-8791","descripcion"=>"Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc,","tipo"=>"J","rif"=>347204571),
	array("razon_social"=>"In Nec Orci Associates","email"=>"semper.dui@dictumaugue.net","direccion"=>"Ap #387-3156 Dolor. St.","telefono"=>"0762-232-4485","descripcion"=>"odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam","tipo"=>"V","rif"=>849427571),
	array("razon_social"=>"Sem Molestie Sodales Institute","email"=>"neque.venenatis@vulputate.edu","direccion"=>"P.O. Box 484, 4510 Tincidunt Street","telefono"=>"0108-375-4883","descripcion"=>"auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc","tipo"=>"V","rif"=>251996191),
	array("razon_social"=>"Accumsan Laoreet Associates","email"=>"Suspendisse.sagittis.Nullam@enim.org","direccion"=>"480-8346 Fringilla. St.","telefono"=>"0457-056-4325","descripcion"=>"et tristique pellentesque, tellus sem","tipo"=>"V","rif"=>241434291),
	array("razon_social"=>"Cras Pellentesque Sed LLP","email"=>"ullamcorper.Duis@lobortistellus.edu","direccion"=>"P.O. Box 940, 3545 Nullam Rd.","telefono"=>"0251-269-7530","descripcion"=>"lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit","tipo"=>"G","rif"=>540420967),
	array("razon_social"=>"Non Massa Company","email"=>"vestibulum.Mauris.magna@Suspendisse.ca","direccion"=>"Ap #153-9723 Donec Avenue","telefono"=>"0286-179-0856","descripcion"=>"vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non,","tipo"=>"G","rif"=>856177586),
	array("razon_social"=>"Ut Ipsum Ac Foundation","email"=>"eros@Fuscefermentum.com","direccion"=>"5305 Ultrices Rd.","telefono"=>"0083-474-1577","descripcion"=>"Quisque ornare","tipo"=>"G","rif"=>112374663),
	array("razon_social"=>"Aliquam Eros Associates","email"=>"pede.nonummy@velitegestas.ca","direccion"=>"Ap #314-6108 Vitae, St.","telefono"=>"0626-429-1649","descripcion"=>"dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse","tipo"=>"J","rif"=>662333263),
	array("razon_social"=>"Scelerisque Dui Suspendisse Corp.","email"=>"dis@dui.org","direccion"=>"P.O. Box 130, 8983 Ut Av.","telefono"=>"0840-114-2578","descripcion"=>"mauris. Suspendisse aliquet molestie tellus.","tipo"=>"J","rif"=>351265618),
	array("razon_social"=>"Pede PC","email"=>"sem@justoeu.org","direccion"=>"P.O. Box 919, 2248 Eu Road","telefono"=>"0172-624-1638","descripcion"=>"Donec dignissim magna a","tipo"=>"J","rif"=>428069690),
	array("razon_social"=>"Velit Aliquam Nisl Limited","email"=>"sit.amet@Aeneanegetmagna.edu","direccion"=>"P.O. Box 608, 8533 Laoreet Rd.","telefono"=>"0658-078-6898","descripcion"=>"ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc","tipo"=>"V","rif"=>230521619),
	array("razon_social"=>"Auctor Quis Consulting","email"=>"vel.nisl.Quisque@nequeSedeget.ca","direccion"=>"Ap #568-5190 Sed Rd.","telefono"=>"0427-452-6916","descripcion"=>"Phasellus elit pede, malesuada vel, venenatis vel,","tipo"=>"V","rif"=>779735213),
	array("razon_social"=>"Placerat Ltd","email"=>"sollicitudin.a.malesuada@nibh.co.uk","direccion"=>"137-5494 Vehicula. Rd.","telefono"=>"0070-695-3053","descripcion"=>"lectus ante dictum mi, ac mattis velit justo nec ante.","tipo"=>"V","rif"=>596788820),
	array("razon_social"=>"Ac Sem PC","email"=>"commodo.at@velsapienimperdiet.net","direccion"=>"839-5748 Donec Avenue","telefono"=>"0303-006-6938","descripcion"=>"lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor","tipo"=>"G","rif"=>999318548),
	array("razon_social"=>"Lobortis Ultrices Vivamus Consulting","email"=>"Proin@milorem.ca","direccion"=>"7039 Lacus. Rd.","telefono"=>"0498-244-5622","descripcion"=>"enim.","tipo"=>"G","rif"=>582212109),
	array("razon_social"=>"Morbi Neque LLP","email"=>"mollis.lectus@Utnec.edu","direccion"=>"891-5149 Vitae, St.","telefono"=>"0337-229-1454","descripcion"=>"tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus,","tipo"=>"G","rif"=>938527369),
	array("razon_social"=>"Faucibus Ut Nulla Limited","email"=>"pede.blandit@justofaucibus.net","direccion"=>"3034 Mi Av.","telefono"=>"0095-773-9947","descripcion"=>"laoreet ipsum. Curabitur consequat, lectus sit amet","tipo"=>"J","rif"=>648828761)
);
$bancos = array (
		"Venezuela" => "Banco de Venezuela",
		"Banesco" => "Banesco",
		"Provincial" => "BBVA Banco Provincial",
		"Mercantil" => "Banco Mercantil",
		"BOD" => "Banco Occidental de Descuento",
		"Bicentenario" => "Bicentenario",
		"Del Tesoro" => "Banco del Tesoro",
		"Bancaribe" => "Bancaribe",
		"Exterior" => "Banco Exterior",
		"BNC" => "Banco Nacional de Crédito",
		"BFC" => "Banco Fondo Común",
		"BVC" => "Venezolano de Crédito",
		"Industrial" => "Banco Industrial de Venezuela",
		"Caroní" => "Banco Caroní",
		"Sofitasa" => "Banco Sofitasa",
		"Banplus" => "Banplus",
		"Plaza" => "Banco Plaza",
		"Activo" => "Banco Activo",
		"Bancrecer" => "Bancrecer",
		"Del Sur" => "Del Sur",
		"100% Banco" => "100% Banco",
		"Agricola" => "Banco Agrícola de Venezuela",
		"Citibank" => "Citibank",
		"BANFANB" => "Banco de la Fuerza Armada Nacional Bolivariana",
		"Bancamiga" => "Bancamiga",
		"Bangente" => "Bangente",
		"Mi Banco" => "Mi Banco",
		"Novo Banco" => "Novo Banco"
);

$estados = array (
		"Amazonas",
		"Anzoátegui",
		"Apure",
		"Aragua",
		"Barinas",
		"Bolívar",
		"Carabobo",
		"Cojedes",
		"Delta Amacuro",
		"Distrito Capital",
		"Falcón",
		"Guárico",
		"Lara",
		"Miranda",
		"Monagas",
		"Mérida",
		"Nueva Esparta",
		"Portuguesa",
		"Sucre",
		"Trujillo",
		"Táchira",
		"Vargas",
		"Yaracuy",
		"Zulia"
);

$status_usuarios = array("Activo","Suspendido","Anulado");

$categorias_juridicos = array(
		"Agricultura",
		"Alimentos/bebidas",
		"Artículos de consumo y venta al por menor",
		"Automóviles y repuestos",
		"Banco/institución financiera",
		"Biotecnología",
		"Causa",
		"Compañía",
		"Compañía de seguros",
		"Computadoras/tecnología",
		"Consultoría/servicios empresariales",
		"Educación",
		"Energía/servicios públicos",
		"Escuela",
		"Escuela primaria",
		"Escuela secundaria",
		"Espacio aéreo/defensa",
		"Iglesia/organización religiosa",
		"Industria",
		"Ingeniería/construcción",
		"Internet/software",
		"Medios/noticias/editorial",
		"Minería/materiales",
		"Organización",
		"Organización comunitaria",
		"Organización gubernamental",
		"Organización no gubernamental (ONG)",
		"Organización política",
		"Organización sin fines de lucro",
		"Partido político",
		"Pequeña empresa",
		"Preescolar",
		"Productos químicos",
		"Salud/belleza",
		"Salud/medicina/productos farmacéuticos",
		"Servicios jurídicos/derecho",
		"Telecomunicaciones",
		"Transporte/flete",
		"Universidad",
		"Viajes/ocio"
);